version: '3.7'
services:
  kong:
      image:  kong_dojot
      user: "kong"
      environment:
        KONG_PROXY_LISTEN: '0.0.0.0:8080'
        KONG_ADMIN_LISTEN: '0.0.0.0:8081'
        KONG_DATABASE: "off"
        KONG_LOG_LEVEL: debug
        KONG_PLUGINS: bundled,helloworld
      ports:
        - "8080:8080/tcp"
        - "127.0.0.1:8081:8081/tcp"
        - "8443:8443/tcp"
        - "127.0.0.1:8444:8444/tcp"
